# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: EasyDesk/action-dotnet-publish@v1
        with:
          # (Optional) The path to the project that should be published.
          # If not specified, defaults to '.'.
          path: '<path>'

          # (Optional) Additional command line arguments to be passed to 'dotnet test'.
          # If not specified, defaults to 'packages'.
          output-dir: '<path-to-output-dir>'

          # (Optional) The build configuration.
          # If not specified, defaults to 'Release'.
          build-configuration: Release

          # (Optional) Whether to skip the build using the '--no-build' flag.
          # If not specified, defaults to true.
          skip-build: true
